# Generated by Django 4.0.1 on 2022-02-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(max_length=15)),
                ('settings', models.BinaryField()),
                ('configuration', models.BinaryField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
