# Generated by Django 4.0.1 on 2022-10-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_game_race_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seed_nonce',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.RunSQL("UPDATE generator_game SET seed_nonce = 'race123' WHERE race_seed = 1;"),
    ]
