# Generated by Django 4.1.5 on 2023-07-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_game_seed_nonce"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="seed_hash",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
