# Staging environment
---
version: '3.8'

services:
  web-generator:
    extends:
      file: docker-compose.prod.yml
      service: web-generator
    env_file:
      - ./.env.staging
      - ./.env.staging.db
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.prod.yml
      service: db
    env_file:
      - ./.env.staging.db

  nginx-proxy:
    extends:
      file: docker-compose.prod.yml
      service: nginx-proxy
    depends_on:
      web-generator:
        condition: service_healthy

  letsencrypt: 
    extends:
      file: docker-compose.prod.yml
      service: letsencrypt
    env_file:
      - ./.env.staging.letsencrypt
    depends_on:
      - nginx-proxy

  ctjot_wiki:
    extends:
      file: docker-compose.prod.yml
      service: ctjot_wiki
    env_file:
      - ./.env.staging.wiki

volumes:
  db_data:
  static_volume:
  certs:
  html:
  vhost:
  acme:
