# Development environment
#
# The JETSOFTIME_PATH environment variable can be set prior to running
# docker-compose (or using deploy.sh script) to override location of
# jetsoftime code to mount into container, e.g. for testing changes
# using local changes to jetsoftime code in another directory.
# By default, it will use the checked out submodule.
---
version: '3.8'

services:
  web-generator:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../ct.sfc:/home/ctjot/web/ct.sfc
      - "${JETSOFTIME_PATH:-../jetsoftime}:/home/ctjot/web/jetsoftime"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
      - ./.env.dev.db

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  db_data:
