# Integration environment
---
version: '3.8'

services:
  web-generator:
    extends:
      file: docker-compose.prod.yml
      service: web-generator
    volumes:
      - ../ct.sfc:/home/ctjot/web/ct.sfc
      - static_volume:/home/ctjot/web/staticfiles
      - "${JETSOFTIME_PATH:-../jetsoftime}:/home/ctjot/web/jetsoftime"
    env_file:
      - ./.env.dev
      - ./.env.dev.db
    environment:
      - "DEBUG=${DEBUG:-0}"
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.prod.yml
      service: db
    env_file:
      - ./.env.dev.db

  nginx-proxy:
    extends:
      file: docker-compose.prod.yml
      service: nginx-proxy
    ports:
      - 8000:80
    environment:
      - DEFAULT_HOST=ctjot.local
    depends_on:
      web-generator:
        condition: service_healthy

volumes:
  db_data:
  static_volume:
  certs:
  html:
  vhost:
  acme:
