version: '3.8'

services:
  web-generator:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../ct.sfc:/home/ctjot/web/ct.sfc
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
      - ./.env.dev.db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  db_data:
