---
name: Shellcheck
on:
  push:
    paths:
      - .github/workflows/shellcheck.yaml
      - '**.sh'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
